name = "grol"
license = "MIT"
licenselink = "https://github.com/aaqaishtyaq/linkbin/blob/trunk/LICENSE.md"
description = "Minimal Hugo theme using a Monospace font and without any tracking or external dependencies with gruvbox theme."
homepage = "https://github.com/aaqaishtyaq/linkbin"
tags = ["blog", "minimal", "monospace", "dark mode", "simple", "clean", "light", "responsive", "fast", "no-js", "no-tracking", "privacy", "gruvbox"]
features = ["blog", "privacy", "responsive", "fast"]
min_version = "0.20"

[author]
  name = "Aaqa Ishtyaq"
  homepage = "aaqa.dewv"

[original]
  name = "morph"
  homepage = "morph.sh"
  repo = "https://github.com/colorchestra/smol"
